name: Snyk Security Scan

on:
  workflow_dispatch

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: npx snyk test --all-projects --json > snyk_results.json

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: snyk-results
        path: snyk_results.json
